"use client";
import { FormEvent, useEffect, useRef, useState } from "react";
import { io, Socket } from "socket.io-client";
import { Send, Users } from "lucide-react";
import { api, socketUrl } from "@/lib/api";
type Profile = { gameName: string; serverNumber: string; allianceName: string }; type ChatMessage = { _id: string; content: string; createdAt: string; user: Profile };
const profileKey = "hos-chat-profile";
function color(user: Profile) { return user.serverNumber === "1895" ? user.allianceName.toLowerCase() === "hos" ? "text-neon-green" : "text-neon-blue" : "text-neon-red"; }
export default function Page() { const [profile,setProfile]=useState<Profile|null>(null),[draft,setDraft]=useState(""),[messages,setMessages]=useState<ChatMessage[]>([]),[online,setOnline]=useState(0),[typing,setTyping]=useState(""); const socket=useRef<Socket|null>(null); const typingTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
  useEffect(()=>{ const value=localStorage.getItem(profileKey); if(value) try { setProfile(JSON.parse(value)); } catch { localStorage.removeItem(profileKey); } api<ChatMessage[]>("/messages").then(items=>setMessages(items.reverse())).catch(()=>{}); },[]);
  useEffect(()=>{ if(!profile||!socketUrl)return; const instance=io(socketUrl,{transports:["websocket"]});socket.current=instance;instance.on("connect",()=>instance.emit("profile",profile));instance.on("message",(message:ChatMessage)=>setMessages(items=>[...items.slice(-99),message]));instance.on("online-users",setOnline);instance.on("typing",(event:{name:string;typing:boolean})=>setTyping(event.typing?`${event.name} is typing…`:""));return()=>{ instance.disconnect(); };},[profile]);
  const saveProfile=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);const next={gameName:String(form.get("gameName")).trim(),serverNumber:String(form.get("serverNumber")).trim(),allianceName:String(form.get("allianceName")).trim()};if(!next.gameName||!next.serverNumber||!next.allianceName)return;localStorage.setItem(profileKey,JSON.stringify(next));setProfile(next);};
  const send=(event:FormEvent)=>{event.preventDefault();if(!draft.trim())return;socket.current?.emit("message",draft.trim(),(result:{ok:boolean})=>{if(!result.ok) alert("Message could not be sent.");});setDraft("");};
  if(!profile)return <main className="grid min-h-screen place-items-center p-4"><form onSubmit={saveProfile} className="glass-panel w-full max-w-md rounded-2xl p-6"><h1 className="text-2xl font-bold text-white">Join alliance chat</h1><p className="mt-2 text-sm text-zinc-400">Your profile and chat activity are saved to alliance records.</p>{[["Game Name","gameName"],["Server Number","serverNumber"],["Alliance Name","allianceName"]].map(([label,name])=><label key={name} className="mt-4 block text-sm text-zinc-300">{label}<input name={name} required maxLength={name === "serverNumber" ? 12 : 40} className="mt-1 w-full rounded-lg border border-white/10 bg-black/30 px-3 py-2.5 outline-none focus:border-neon-blue"/></label>)}<button className="mt-6 w-full rounded-lg bg-neon-blue/20 py-3 font-bold text-neon-blue ring-1 ring-neon-blue/50 hover:bg-neon-blue hover:text-black">Enter chat</button></form></main>;
  return <main className="mx-auto flex min-h-screen w-full max-w-4xl flex-col p-4 pt-20 sm:p-8 sm:pt-24"><header className="glass-panel flex items-center justify-between rounded-t-2xl px-5 py-4"><div><h1 className="font-bold tracking-widest text-white">HOS CHAT</h1><p className="text-xs text-zinc-400">Server 1895 communications</p></div><span className="flex items-center gap-2 text-sm text-neon-green"><Users size={15}/>{online} online</span></header><section className="glass-panel flex min-h-0 flex-1 flex-col rounded-b-2xl"><div className="min-h-[55vh] flex-1 space-y-4 overflow-y-auto p-5">{messages.map(message=><article key={message._id}><div className="flex items-baseline gap-2"><strong className={color(message.user)}>{message.user.gameName}</strong><span className="text-xs text-zinc-500">[{message.user.allianceName.slice(0,3).toUpperCase()}] · {new Date(message.createdAt).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</span></div><p className="mt-1 break-words text-sm text-zinc-200">{message.content}</p></article>)}</div><p className="h-5 px-5 text-xs text-zinc-500">{typing}</p><form onSubmit={send} className="flex gap-2 border-t border-white/10 p-3"><button type="button" onClick={()=>setDraft(value=>`${value} 😊`)} className="rounded px-2 text-lg">😊</button><input value={draft} onChange={e=>{setDraft(e.target.value);socket.current?.emit("typing",true);if(typingTimer.current)clearTimeout(typingTimer.current);typingTimer.current=setTimeout(()=>socket.current?.emit("typing",false),800);}} maxLength={1000} placeholder="Message the alliance…" className="min-w-0 flex-1 rounded-lg bg-black/30 px-3 py-2 outline-none focus:ring-1 focus:ring-neon-blue"/><button className="rounded-lg bg-neon-blue/20 p-2 text-neon-blue ring-1 ring-neon-blue/50"><Send size={18}/></button></form></section></main>;
}
