const mongoose = require('mongoose');
const { Schema } = mongoose;
const opts = { timestamps: true, strict: 'throw' };
const adminSchema = new Schema({ username: { type: String, required: true, unique: true, trim: true, lowercase: true }, email: { type: String, required: true, unique: true, trim: true, lowercase: true }, password: { type: String, required: true }, role: { type: String, enum: ['admin'], default: 'admin' } }, opts);
const userSchema = new Schema({ gameName: { type: String, required: true, trim: true, maxlength: 40 }, serverNumber: { type: String, required: true, trim: true, maxlength: 12 }, allianceName: { type: String, required: true, trim: true, maxlength: 40 }, socketId: { type: String }, lastSeenAt: { type: Date, default: Date.now } }, opts);
const settingsSchema = new Schema({ key: { type: String, default: 'site', unique: true }, websiteTitle: String, banner: String, logo: String, navigation: [Schema.Types.Mixed], themeColors: Schema.Types.Mixed, heroContent: Schema.Types.Mixed, footer: String, primaryColor: String, youtubeLink: String, discordLink: String, galleryUploadsPer10Min: { type: Number, min: 1, max: 20, default: 2 }, currentSvsValues: [Schema.Types.Mixed], toolSettings: Schema.Types.Mixed, lastSvsAutoAdvance: String, recruitmentEmailSenderName: { type: String, default: 'HOS Recruitment' }, recruitmentEmailReceiver: { type: String, default: '' }, recruitmentEmailLimitPer30Min: { type: Number, min: 1, max: 20, default: 2 }, chatMessagesLimitPerMin: { type: Number, min: 5, max: 120, default: 30 } }, opts);
const toolSchema = new Schema({ toolId: { type: String, required: true, unique: true, trim: true }, title: { type: String, required: true, maxlength: 80, trim: true }, description: { type: String, maxlength: 500, trim: true }, icon: { type: String, maxlength: 80 }, color: { type: String, match: /^#[0-9A-Fa-f]{6}$/ }, category: { type: String, maxlength: 50, trim: true }, displayOrder: { type: Number, required: true, index: true }, link: { type: String, required: true, maxlength: 2048 }, enabled: { type: Boolean, default: true } }, opts);
const gallerySchema = new Schema({ imageUrl: { type: String, required: true }, publicId: { type: String, required: true, unique: true }, uploader: { type: String, required: true, maxlength: 40 }, description: { type: String, maxlength: 300, default: '' }, likes: { type: Number, default: 0, min: 0 } }, opts);
const galleryUploadSchema = new Schema({ userKey: { type: String, required: true, index: true }, imageUrl: String }, opts);
const messageSchema = new Schema({ userId: { type: Schema.Types.ObjectId, ref: 'ChatUser', required: true, index: true }, content: { type: String, required: true, trim: true, maxlength: 1000 }, createdAt: { type: Date, default: Date.now, expires: 60 * 60 * 24 * 30, index: true } }, { strict: 'throw' });
const eventSchema = new Schema({ title: { type: String, required: true, trim: true, maxlength: 120 }, description: { type: String, maxlength: 1000 }, startsAt: { type: Date, required: true, index: true }, timezone: { type: String, default: 'America/New_York' }, hidden: { type: Boolean, default: false, index: true } }, opts);
const applicationSchema = new Schema({ playerName: { type: String, required: true, trim: true, maxlength: 60 }, server: { type: String, trim: true, maxlength: 12, default: '' }, alliance: { type: String, trim: true, maxlength: 40, default: '' }, power: { type: String, trim: true, maxlength: 30, default: '' }, discord: { type: String, trim: true, maxlength: 200, default: '' }, email: { type: String, required: true, trim: true, lowercase: true }, message: { type: String, required: true, maxlength: 2000 }, status: { type: String, enum: ['new', 'reviewing', 'accepted', 'rejected'], default: 'new', index: true }, ipAddress: { type: String, index: true } }, opts);
const analyticsSchema = new Schema({ day: { type: String, unique: true, index: true }, visitors: { type: Number, default: 0 }, galleryUploads: { type: Number, default: 0 }, applications: { type: Number, default: 0 }, messages: { type: Number, default: 0 }, popularTools: { type: Map, of: Number, default: {} } }, opts);
const assistantMessageSchema = new Schema({ sessionId: { type: String, required: true, trim: true, maxlength: 120, index: true }, role: { type: String, enum: ['user', 'ai'], required: true }, content: { type: String, required: true, trim: true, maxlength: 2000 }, gameName: { type: String, trim: true, maxlength: 40 }, serverNumber: { type: String, trim: true, maxlength: 12 }, allianceName: { type: String, trim: true, maxlength: 40 } }, opts);
const svsSchema = new Schema({ position: { type: Number, required: true, unique: true, min: 1, max: 10 }, week: { type: String, required: true, match: /^\d{4}-W\d{2}$/ }, date: { type: Date }, url: { type: String, required: true, maxlength: 2048 } }, opts);
module.exports = {
 Admin: mongoose.models.Admin || mongoose.model('Admin', adminSchema), User: mongoose.models.ChatUser || mongoose.model('ChatUser', userSchema), Settings: mongoose.models.Settings || mongoose.model('Settings', settingsSchema), Tool: mongoose.models.Tool || mongoose.model('Tool', toolSchema), Gallery: mongoose.models.Gallery || mongoose.model('Gallery', gallerySchema), GalleryUpload: mongoose.models.GalleryUpload || mongoose.model('GalleryUpload', galleryUploadSchema), Message: mongoose.models.Message || mongoose.model('Message', messageSchema), Event: mongoose.models.Event || mongoose.model('Event', eventSchema), Application: mongoose.models.Application || mongoose.model('Application', applicationSchema), Analytics: mongoose.models.Analytics || mongoose.model('Analytics', analyticsSchema), AssistantMessage: mongoose.models.AssistantMessage || mongoose.model('AssistantMessage', assistantMessageSchema), SVSHistory: mongoose.models.SVSHistory || mongoose.model('SVSHistory', svsSchema)
};
